#%RAML 1.0 Library
types:
  username:
    type: string
  password:
    type: string
  createuser: |
    {
      "type": "object",
      "$schema": "http://json-schema.org/draft-03/schema",
      "id": "http://jsonschema.net",
      "required": true,
      "properties": {
        "username": {
          "type": "string",
          "required": true,
          "minLength": 4,
          "maxLength": 6
        },
        "password": {
          "type": "string",
          "required": true
        },
        "name": {
          "type": "string",
          "required": true
        }
      }
    }
  readuser: |
    {
      "type": "object",
      "$schema": "http://json-schema.org/draft-03/schema",
      "id": "http://jsonschema.net",
      "required": true,
      "properties": {
        "username": {
          "type": "string",
          "required": true,
          "minLength": 4,
          "maxLength": 6
        },
        "password": {
          "type": "string",
          "required": true
        },
        "name": {
          "type": "string",
          "required": true
        }
      }
    }
  updateuser: |
    {
      "type": "object",
      "$schema": "http://json-schema.org/draft-03/schema",
      "id": "http://jsonschema.net",
      "required": true,
      "properties": {
        "username": {
          "type": "string",
          "required": true,
          "minLength": 4,
          "maxLength": 6
        },
        "password": {
          "type": "string",
          "required": true
        },
        "lastlogin": {
          "type": "string",
          "required": true
        }
      }
    }
  deleteuser: |
    {
      "type": "object",
      "$schema": "http://json-schema.org/draft-03/schema",
      "id": "http://jsonschema.net",
      "required": true,
      "properties": {
        "username": {
          "type": "string",
          "required": true,
          "minLength": 4,
          "maxLength": 6
        },
        "name": {
          "type": "string",
          "required": true
        }
      }
    }
  userq: |
    {
      "type": "object",
      "$schema": "http://json-schema.org/draft-03/schema",
      "id": "http://jsonschema.net",
      "required": true,
      "properties": {
        "msgtype": {
          "type": "string",
          "required": true
        },
        "message": {
          "type": "object",
          "$schema": "http://json-schema.org/draft-03/schema",
          "id": "http://jsonschema.net",
          "required": true,
          "properties": {
            "username": {
              "type": "string",
              "required": true,
              "minLength": 4,
              "maxLength": 6
            },
            "password": {
              "type": "string",
              "required": true
            },
            "name": {
              "type": "string",
              "required": false
            },
            "lastlogin": {
              "type": "string",
              "required": false
            }
          }
        }
      }
    }
  createproduct: |
    {
      "type": "object",
      "$schema": "http://json-schema.org/draft-03/schema",
      "id": "http://jsonschema.net",
      "required": true,
      "properties": {
        "title": {
          "type": "string",
          "required": true
        },
        "description": {
          "type": "string",
          "required": true
        },
        "price": {
          "type": "number",
          "required": true
        },
        "discountPercentage": {
          "type": "number",
          "required": true
        },
        "rating": {
          "type": "number",
          "required": true
        },
        "stock": {
          "type": "number",
          "required": true
        },
        "brand": {
          "type": "string",
          "required": true
        },
        "category": {
          "type": "string",
          "required": true
        },
        "thumbnail": {
          "type": "string",
          "required": true
        }       
      }
    }
  deleteproduct: |
    {
      "type": "object",
      "$schema": "http://json-schema.org/draft-03/schema",
      "id": "http://jsonschema.net",
      "required": true,
      "properties": {
        "id": {
          "type": "string",
          "required": true
        }
      }
    }