#%RAML 1.0
title: estoreexpress-subscriberapi-mule

uses:
  apiLib: datatypes/apilib.raml

/ping:
  get:
    description: ping
    queryParameters:
      username:
        description: username
        type: apiLib.username
        required: false
      password:
        description: password
        type: apiLib.password
        required: false
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              example1: !include examples/test1.raml
              example2: !include examples/test2.raml
/createuser:
  post:
    description: createuser
    body:
        application/json:
          type:  apiLib.createuser
          example: |
            {
              "username": "test1",
              "password": "test",
              "name": "test1"
            }
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              example1: !include examples/createuser/test1.raml
              example2: !include examples/createuser/test2.raml
/updateuser:
  post:
    description: updateuser
    body:
        application/json:
          type:  apiLib.updateuser
          example: |
            {
              "username": "test1",
              "password": "test",
              "lastlogin": "2016-01-01"
            }
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              example1: !include examples/updateuser/test1.raml
/deleteuser:
  post:
    description: deleteuser
    body:
        application/json:
          type:  apiLib.deleteuser
          example: |
            {
              "username": "test1",
              "name": "test1"
            }
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              example1: !include examples/deleteuser/test1.raml
/readuser:
  get:
    description: readuser
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              example1: !include examples/readuser/test1.raml
/testuserq:
  post:
    description: testuserq
    body:
        application/json:
          type:  apiLib.userq
          example: |
            {
              "msgtype": "register",
              "message": {
                "username": "test1",
                "password": "test",
                "name": "testname"
              }
            }
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              example1: !include examples/testuserq/register.raml
/testerrorq:
  post:
    description: testerrorq
    body:
        application/json:
          example: |
            {"transactionId":"9e56521b.ec30.4709.b477.c743f3854063","msgtype":"register","transactionstatus":"Failed","error":{"description":"The client with ID: test1 is already registered","type":"APPERROR:CLIENT_ALREADY_EXISTS","cause":"The client with ID: test1 is already registered"}}
    responses:
      200:
        body:
          application/json:
            type: object
            examples:
              example1: !include examples/testerrorq/errorcode-0001.raml

